#!/usr/bin/env python3
"""Export a LightGBM model as self-contained C++ arrays."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

import lightgbm as lgb


@dataclass
class FlatNode:
    left: int
    right: int
    category_offset: int
    threshold: float
    feature: int
    category_base: int
    category_word_count: int
    categorical: bool
    default_left: bool


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("model", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--namespace", default="delay::model")
    parser.add_argument("--function", default="predict_log_delay")
    return parser.parse_args()


def format_array(name: str, ctype: str, values: list, formatter=str) -> str:
    lines = [f"inline constexpr std::array<{ctype}, {len(values)}> {name}{{{{"]
    row: list[str] = []
    for value in values:
        row.append(formatter(value))
        if len(row) == 12:
            lines.append("    " + ", ".join(row) + ",")
            row.clear()
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("}};")
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    if not re.fullmatch(r"[A-Za-z_]\w*(?:::[A-Za-z_]\w*)*", args.namespace):
        raise ValueError(f"invalid C++ namespace: {args.namespace}")
    if not re.fullmatch(r"[A-Za-z_]\w*", args.function):
        raise ValueError(f"invalid C++ function name: {args.function}")
    dump = lgb.Booster(model_file=str(args.model)).dump_model()
    if not (dump["objective"] == "regression" or dump["objective"].startswith("regression_l1")):
        raise ValueError(f"unsupported objective: {dump['objective']}")

    nodes: list[FlatNode] = []
    leaves: list[float] = []
    category_words: list[int] = []

    def flatten(tree: dict) -> int:
        if "leaf_index" in tree:
            index = len(leaves)
            leaves.append(float(tree["leaf_value"]))
            return -index - 1
        index = len(nodes)
        nodes.append(FlatNode(0, 0, 0, 0.0, 0, 0, 0, False, False))
        categorical = tree["decision_type"] == "=="
        if categorical:
            categories = sorted(int(value) for value in str(tree["threshold"]).split("||"))
            category_base = categories[0] // 64
            category_word_count = categories[-1] // 64 - category_base + 1
            words = [0] * category_word_count
            for category in categories:
                words[category // 64 - category_base] |= 1 << (category % 64)
            category_offset = len(category_words)
            category_words.extend(words)
            threshold = 0.0
        else:
            category_offset = 0
            category_base = 0
            category_word_count = 0
            threshold = float(tree["threshold"])
        left = flatten(tree["left_child"])
        right = flatten(tree["right_child"])
        nodes[index] = FlatNode(
            left=left,
            right=right,
            category_offset=category_offset,
            threshold=threshold,
            feature=int(tree["split_feature"]),
            category_base=category_base,
            category_word_count=category_word_count,
            categorical=categorical,
            default_left=bool(tree["default_left"]),
        )
        return index

    roots = [flatten(info["tree_structure"]) for info in dump["tree_info"]]
    pandas_categories = dump["pandas_categorical"]
    category_names = {
        4: "kSourcePortCategories",
        5: "kTargetPortCategories",
        12: "kEffectiveSourcePortCategories",
        13: "kEndpointPairCategories",
    }
    category_arrays: list[str] = []
    for index, name in category_names.items():
        values = pandas_categories[index]
        if not all(isinstance(value, int) for value in values):
            raise ValueError(f"{name} contains non-integer categories")
        category_arrays.append(format_array(name, "std::int32_t", values))

    node_lines = [f"inline constexpr std::array<Node, {len(nodes)}> kNodes{{{{"]
    for node in nodes:
        node_lines.append(
            "    Node{" +
            f"{node.left}, {node.right}, {node.category_offset}u, " +
            f"{node.threshold:.17g}, {node.feature}u, {node.category_base}u, " +
            f"{node.category_word_count}u, " +
            f"{str(node.categorical).lower()}, {str(node.default_left).lower()}" +
            "},"
        )
    node_lines.append("}};")

    content = f"""// Generated by scripts/export_lightgbm_cpp.py. Do not edit manually.
#pragma once

#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>

namespace {args.namespace} {{

struct Node {{
    std::int32_t left;
    std::int32_t right;
    std::uint32_t category_offset;
    double threshold;
    std::uint16_t feature;
    std::uint16_t category_base;
    std::uint16_t category_word_count;
    bool categorical;
    bool default_left;
}};

{chr(10).join(node_lines)}

{format_array("kLeaves", "double", leaves, lambda value: f"{value:.17g}")}

{format_array("kRoots", "std::int32_t", roots)}

{format_array("kCategoryWords", "std::uint64_t", category_words, lambda value: f"0x{value:016x}ULL")}

{chr(10).join(category_arrays)}

template <std::size_t Size>
inline std::int32_t category_code(
    const std::array<std::int32_t, Size>& categories, std::int32_t raw_value) {{
    const auto iterator = std::lower_bound(categories.begin(), categories.end(), raw_value);
    if (iterator == categories.end() || *iterator != raw_value) {{
        return -1;
    }}
    return static_cast<std::int32_t>(iterator - categories.begin());
}}

inline double {args.function}(
    const std::array<double, {len(dump['feature_names'])}>& features,
    std::size_t tree_limit = kRoots.size()) {{
    double result = 0.0;
    for (std::size_t tree = 0; tree < tree_limit && tree < kRoots.size(); ++tree) {{
        const auto root = kRoots[tree];
        std::int32_t index = root;
        while (index >= 0) {{
            const auto& node = kNodes[static_cast<std::size_t>(index)];
            bool take_left;
            if (node.categorical) {{
                const auto category = static_cast<std::int32_t>(features[node.feature]);
                if (category < 0) {{
                    take_left = node.default_left;
                }} else {{
                    const auto word = static_cast<std::uint32_t>(category) / 64u;
                    if (word < node.category_base ||
                        word >= static_cast<std::uint32_t>(node.category_base) + node.category_word_count) {{
                        take_left = false;
                    }} else {{
                        const auto bits = kCategoryWords[
                            node.category_offset + word - node.category_base];
                        take_left = (bits & (std::uint64_t{{1}} << (category % 64))) != 0;
                    }}
                }}
            }} else {{
                take_left = features[node.feature] <= node.threshold;
            }}
            index = take_left ? node.left : node.right;
        }}
        result += kLeaves[static_cast<std::size_t>(-index - 1)];
    }}
    return result;
}}

}}  // namespace {args.namespace}
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(
        f"exported {len(roots)} trees, {len(nodes)} nodes, {len(leaves)} leaves, "
        f"and {len(category_words)} category words to {args.output}"
    )


if __name__ == "__main__":
    main()
